#define NUM                              1
#define DEC                              2
#define ID                               3
#define STR                              4
#define ASGN_OP                          5
#define LT_OP                            6
#define GT_OP                            7
#define ADD_OP                           8
#define SUB_OP                           9
#define MUL_OP                          10
#define DIV_OP                          11
#define MOD_OP                          12
#define AND_OP                          13
#define OR_OP                           14
#define XOR_OP                          15
#define NOT_OP                          16
#define LOGAND                          17
#define LOGOR                           18
#define LOGNOT                          19
#define DOT_OP                          20
#define PTR_OP                          21
#define INC_OP                          22
#define DEC_OP                          23
#define SHL_OP                          24
#define SHR_OP                          25
#define LE_OP                           26
#define GE_OP                           27
#define EQ_OP                           28
#define NE_OP                           29
#define MULASGN                         30
#define DIVASGN                         31
#define MODASGN                         32
#define ADDASGN                         33
#define SUBASGN                         34
#define SHLASGN                         35
#define SHRASGN                         36
#define ANDASGN                         37
#define XORASGN                         38
#define ORASGN                          39
#define SIZEOF                          40
#define ELLIPSIS                        41
#define TYPEDEF                         42
#define STATIC                          43
#define CONST                           44
#define VOID                            45
#define CHAR                            46
#define SHORT                           47
#define INT                             48
#define LONG                            49
#define FLOAT                           50
#define DOUBLE                          51
#define TYPE                            52
#define IF                              53
#define ELSE                            54
#define FOR                             55
#define WHILE                           56
#define DO                              57
#define CONTINUE                        58
#define BREAK                           59
#define RETURN                          60
#define GOTO                            61
#define LP                              62
#define RP                              63
#define LS                              64
#define RS                              65
#define LB                              66
#define RB                              67
#define COM                             68
#define SEM                             69
#define COL                             70
#define QUE                             71
